# Generated by Django 2.1 on 2018-08-26 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razaoSocial', models.CharField(max_length=255)),
                ('cnpj', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255, null=True)),
                ('password', models.CharField(max_length=255, null=True)),
                ('filtro', models.CharField(max_length=255)),
                ('proceso_interno', models.IntegerField(null=True)),
                ('processo_externo', models.IntegerField(null=True)),
                ('keyWords', models.CharField(max_length=255)),
                ('processoInterno', models.IntegerField()),
                ('processoExterno', models.IntegerField()),
                ('transportadora', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'empresa',
                'verbose_name_plural': 'empresas',
                'db_table': 'empresas',
            },
        ),
    ]
