# Generated by Django 2.1 on 2018-08-26 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='processoExterno',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='processoInterno',
            field=models.IntegerField(null=True),
        ),
    ]
